PaddleHQ/paddle-python-sdk

CHANGELOG.md
paddle_billing/Client.py
setup.py

- Fixed [bug](https://github.com/PaddleHQ/paddle-python-sdk/pull/12) - corrected import in `NotificationSettingCollection`.

Release: 0.1.2

---

paddle_billing/Entities/Collections/AddressCollection.py
paddle_billing/Entities/Collections/AdjustmentCollection.py
paddle_billing/Entities/Collections/BusinessCollection.py
paddle_billing/Entities/Collections/Collection.py
paddle_billing/Entities/Collections/CreditBalanceCollection.py
paddle_billing/Entities/Collections/CustomerCollection.py
paddle_billing/Entities/Collections/DiscountCollection.py
paddle_billing/Entities/Collections/EventCollection.py
paddle_billing/Entities/Collections/EventTypeCollection.py
paddle_billing/Entities/Collections/NotificationCollection.py
paddle_billing/Entities/Collections/NotificationLogCollection.py
paddle_billing/Entities/Collections/NotificationSettingCollection.py
paddle_billing/Entities/Collections/PriceCollection.py
paddle_billing/Entities/Collections/ProductCollection.py
paddle_billing/Entities/Collections/ReportCollection.py
paddle_billing/Entities/Collections/SubscriptionCollection.py
paddle_billing/Entities/Collections/SubscriptionPreviewCollection.py
paddle_billing/Entities/Collections/TransactionCollection.py
paddle_billing/Entities/Collections/TransactionPreviewCollection.py
paddle_billing/Entities/Collections/TransactionsDataCollection.py

Our current implementation of Collections is working great but you lose IDE support entirely. This is a really quick quality of life improvement by making the Collection generic. 
Before: 
After:

feat: Improved IDE support for Collection types

---

CHANGELOG.md
paddle_billing/Client.py
setup.py

fix:version bump

---

CHANGELOG.md
paddle_billing/Client.py
setup.py
tests/Functional/Client/test_Client.py
tests/Utils/TestClient.py

- Fixed [bug](https://github.com/PaddleHQ/paddle-python-sdk/pull/24) - set default timeout.

Release: 0.2.2

---

CHANGELOG.md
paddle_billing/Resources/NotificationSettings/NotificationSettingsClient.py
paddle_billing/Resources/NotificationSettings/Operations/ListNotificationSettings.py
paddle_billing/Resources/NotificationSettings/Operations/__init__.py
tests/Functional/Resources/NotificationSettings/_fixtures/response/list_paginated_page_one.json
tests/Functional/Resources/NotificationSettings/_fixtures/response/list_paginated_page_two.json
tests/Functional/Resources/NotificationSettings/test_NotificationSettingsClient.py

- Support notification settings pagination, see [related changelog](https://developer.paddle.com/changelog/2024/notification-settings-pagination)
- Support notification settings `active` filter

feat: Add notification list pagination and filter

---

paddle_billing/Entities/Shared/Disposition.py

- Correct Disposition enum types - fixed #30

fix: Correct Disposition enum types

---

paddle_billing/Exceptions/SdkExceptions/InvalidArgumentException.py
paddle_billing/Resources/Addresses/Operations/ListAddresses.py
paddle_billing/Resources/Adjustments/Operations/ListAdjustments.py
paddle_billing/Resources/Businesses/Operations/ListBusinesses.py
paddle_billing/Resources/Customers/Operations/ListCreditBalances.py
paddle_billing/Resources/Customers/Operations/ListCustomers.py
paddle_billing/Resources/Discounts/Operations/ListDiscounts.py
paddle_billing/Resources/Notifications/Operations/ListNotifications.py
paddle_billing/Resources/Prices/Operations/ListPrices.py
paddle_billing/Resources/Prices/PricesClient.py
paddle_billing/Resources/PricingPreviews/Operations/PreviewPrice.py
paddle_billing/Resources/Products/Operations/ListProducts.py
paddle_billing/Resources/Products/ProductsClient.py
paddle_billing/Resources/Reports/Operations/CreateReport.py
paddle_billing/Resources/Reports/Operations/ListReports.py
paddle_billing/Resources/Subscriptions/Operations/ListSubscriptions.py
paddle_billing/Resources/Subscriptions/SubscriptionsClient.py
paddle_billing/Resources/Transactions/Operations/ListTransactions.py
paddle_billing/Resources/Transactions/TransactionsClient.py
tests/Unit/Resources/Addresses/Operations/test_ListAddresses.py
tests/Unit/Resources/Adjustments/Operations/test_ListAdjustments.py
tests/Unit/Resources/PricingPreviews/Operations/test_PreviewPrice.py

- Add validation for pricing preview items
- Fixed invalid array type exception messages

fix: Add validation for pricing preview items

---

CHANGELOG.md
paddle_billing/Entities/Adjustment.py
paddle_billing/Entities/Adjustments/AdjustmentTaxRatesUsed.py
paddle_billing/Entities/Adjustments/AdjustmentTotals.py
paddle_billing/Entities/Adjustments/__init__.py
paddle_billing/Notifications/Entities/Adjustment.py
paddle_billing/Notifications/Entities/Adjustments/AdjustmentTaxRatesUsed.py
paddle_billing/Notifications/Entities/Adjustments/AdjustmentTotals.py
paddle_billing/Notifications/Entities/Adjustments/__init__.py
tests/Functional/Resources/Adjustments/_fixtures/response/full_entity.json
tests/Functional/Resources/Adjustments/_fixtures/response/list_default.json
tests/Functional/Resources/Adjustments/_fixtures/response/minimal_entity.json
tests/Functional/Resources/Adjustments/test_AdjustmentsClient.py
tests/Functional/Resources/Notifications/_fixtures/response/list_default.json
tests/Functional/Resources/Notifications/test_NotificationsClient.py

- Support for `tax_rates_used` on Adjustments

feat: Add tax_rates_used to Adjustments

---

CHANGELOG.md
paddle_billing/Entities/AdjustmentCreditNote.py
paddle_billing/Entities/CreditNote.py
paddle_billing/Resources/Adjustments/AdjustmentsClient.py
paddle_billing/Resources/Adjustments/Operations/GetCreditNote.py
paddle_billing/Resources/Adjustments/Operations/__init__.py
tests/Functional/Resources/Adjustments/_fixtures/response/get_credit_note_default.json
tests/Functional/Resources/Adjustments/test_AdjustmentsClient.py
tests/Functional/Resources/Transactions/test_TransactionsClient.py

- Added `AdjustmentsClient.get_credit_note`, see [related changelog](https://developer.paddle.com/changelog/2024/generate-adjustments-credit-notes)

feat: Added AdjustmentsClient.get_credit_note

---

tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_one.json
tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_two.json
tests/Functional/Resources/Transactions/test_TransactionsClient.py

- Fixed test `TestTransactionsClient.test_list_transaction_can_paginate`

test: Add test coverage for transaction pagination

---

examples/catalog_management.py
examples/event_polling.py
examples/get_products.py
examples/logger.py
paddle_billing/Exceptions/SdkExceptions/MalformedResponse.py

- Updated examples for latest SDK version
- Unused exception `paddle_billing.Exceptions.SdkExceptions.MalformedResponse`

docs: Update examples

---

.github/workflows/lint.yml
.pre-commit-config.yaml
examples/catalog_management.py
examples/event_polling.py
examples/get_products.py

- Formatter checks on pre-commit and GitHub action
---
https://github.com/PaddleHQ/paddle-python-sdk/actions/runs/11161481293/job/31024114665?pr=52
```
Oh no! 💥 💔 💥
1 file would be reformatted, 548 files would be left unchanged.
Error: Process completed with exit code 1.
```
---
Formatting should have been applied in #51 
Pre-commit check should have been added in #49

feat: Run formatter checks

---

CHANGELOG.md
setup.py

- Added missing initialization file for `paddle_billing.Resources.IPAddresses`
#59

fix: Add missing initialization file for paddle_billing.Resources.IPAddresses

---

tests/Functional/Resources/PaymentMethods/_fixtures/response/full_entity_card.json
tests/Functional/Resources/PaymentMethods/_fixtures/response/list_default.json
tests/Functional/Resources/PaymentMethods/_fixtures/response/list_paginated_page_one.json
tests/Functional/Resources/PaymentMethods/_fixtures/response/list_paginated_page_two.json
tests/Functional/Resources/PaymentMethods/test_PaymentMethodsClient.py

- Correct payment method test fixtures

test: Correct payment method test fixtures

---

CHANGELOG.md
paddle_billing/Entities/NotificationSetting.py
paddle_billing/Entities/NotificationSettings/NotificationSettingTrafficSource.py
paddle_billing/Entities/NotificationSettings/__init__.py
paddle_billing/Resources/NotificationSettings/Operations/CreateNotificationSetting.py
paddle_billing/Resources/NotificationSettings/Operations/ListNotificationSettings.py
paddle_billing/Resources/NotificationSettings/Operations/UpdateNotificationSetting.py
tests/Functional/Resources/NotificationSettings/_fixtures/request/create_traffic_all.json
tests/Functional/Resources/NotificationSettings/_fixtures/request/create_traffic_platform.json
tests/Functional/Resources/NotificationSettings/_fixtures/request/create_traffic_simulation.json
tests/Functional/Resources/NotificationSettings/_fixtures/request/update_traffic_all.json
tests/Functional/Resources/NotificationSettings/_fixtures/request/update_traffic_platform.json
tests/Functional/Resources/NotificationSettings/_fixtures/request/update_traffic_simulation.json
tests/Functional/Resources/NotificationSettings/_fixtures/response/full_entity.json
tests/Functional/Resources/NotificationSettings/_fixtures/response/list_default.json
tests/Functional/Resources/NotificationSettings/_fixtures/response/list_paginated_page_one.json
tests/Functional/Resources/NotificationSettings/_fixtures/response/list_paginated_page_two.json
tests/Functional/Resources/NotificationSettings/_fixtures/response/minimal_entity.json
tests/Functional/Resources/NotificationSettings/test_NotificationSettingsClient.py

- Added `traffic_source` property to `paddle_billing.Entities.NotificationSetting` entity

feat: Add support for notification settings traffic source

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Entities/Adjustment.py
setup.py
tests/Functional/Resources/Adjustments/test_AdjustmentsClient.py

- Adjustment type in responses is now the correct type

fix: Adjustment type in responses is now the correct type

---

CHANGELOG.md
paddle_billing/Client.py
setup.py

https://github.com/PaddleHQ/paddle-python-sdk/compare/v1.4.0...docs/release-1.5.0
---
- Added `transactions.revise` operation to revise a transaction and added `revised_at` to `Transaction` entity, see [related changelog](https://developer.paddle.com/changelog/2024/revise-transaction-customer-information?utm_source=dx&utm_medium=paddle-python-sdk).
- Added support for `transaction.revised` notification, see [related changelog](https://developer.paddle.com/changelog/2024/revise-transaction-customer-information?utm_source=dx&utm_medium=paddle-python-sdk).
- Added simulation API support [related changelog](https://developer.paddle.com/changelog/2024/webhook-simulator?utm_source=dx&utm_medium=paddle-python-sdk)
- `Client.simulations.create`
- `Client.simulations.update`
- …

docs: Release 1.5.0

---

README.md

- Improved Verifier docs in README
Closes #85

docs: Webhook verification docs

---

paddle_billing/Resources/Reports/ReportsClient.py

fix: Type hints

---

CHANGELOG.md
paddle_billing/Client.py
setup.py

https://github.com/PaddleHQ/paddle-python-sdk/compare/v1.6.1...docs/release-1-7-0
---
- Added support for Korean local payment methods, see [related changelog](https://developer.paddle.com/changelog/2024/korean-payment-methods?utm_source=dx&utm_medium=paddle-python-sdk).
- Added support for `balance` reports, see [related changelog](https://developer.paddle.com/changelog/2025/balance-reports?utm_source=dx&utm_medium=paddle-python-sdk).
- Added support for API key events, see [related changelog](https://developer.paddle.com/changelog/2025/api-key-improvements?utm_source=dx&utm_medium=paddle-python-sdk).
- Added support for discount mode
- Added support for discount group resources, see [related changelog](https://developer.paddle.com/changelog/2025/discount-groups?utm_source=dx&utm_medium=p …

docs(release): v1.7.0

---

CHANGELOG.md
paddle_billing/Client.py
setup.py

- Added support for client tokens see [related changelog](https://developer.paddle.com/changelog/2025/client-side-token-api?utm_source=dx&utm_medium=paddle-python-sdk)
---
https://github.com/PaddleHQ/paddle-python-sdk/compare/v1.7.0...docs/release-1-8-0

docs(release): v1.8.0
