PaddleHQ/paddle-python-sdk

README.md

Problem: The code block showcasing webhook verification has a missing parenthesis.

chore: Webhook signature verification readme block updated

---

.github/workflows/testing.yml
.gitignore
.idea/.gitignore
CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Resources/Businesses/Operations/UpdateBusiness.py
setup.py

- Fixed a [bug](https://github.com/PaddleHQ/paddle-python-sdk/issues/7) with `UpdateBusiness` operation.
---
Fixes: #7

Fixed a bug with UpdateBusiness operation

---

paddle_billing/Entities/Collections/NotificationSettingCollection.py
tests/Functional/Resources/NotificationSettings/test_NotificationSettingsClient.py

SDK incorrectly imported `Notification` entity instead of `NotificationSetting` when pulling a list of notification settings.
Verified it by installing the package form the head repo and running the same command - no error.
Error log:
```
In [10]: client.notification_settings.list()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 client.notification_settings.list()
File ~/env/paddle_billing/Resources/NotificationSettings/NotificationSettingsClient.py:23, in NotificationSettingsClient.list(self)
20 self.response = self.client.get_raw('/notification-settings')
21 parser        = ResponseParser(self.response)
---> 23 return …
```

fix: notification settings collection import

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Exceptions/ApiError.py
paddle_billing/ResponseParser.py
setup.py
tests/Functional/Client/test_Client.py
tests/Functional/Resources/Addresses/test_AddressesClient.py
tests/Utils/TestClient.py
tests/Utils/TestLogger.py
tests/conftest.py

- `Client._make_request` now raises an `ApiError` (or resolved sub class if implemented, e.g. `AddressApiError`), which provides the following properties:
- `error_type`
- `error_code`
- `detail`
- `docs_url`
- `field_errors` (list)
- `field`
- `error`
- `ApiError` extends `requests.HTTPError` and so also has `response` object available.
- `Client._make_request` now logs `repr(api_error)` to provide more detail about the error.
---
Relates to https://github.com/PaddleHQ/paddle-python-sdk/issues/10

fix: Raise ApiError for request errors

---

paddle_billing/Client.py

Right now the SDK has no timeout configured. If Paddle services don't respond the request on my side will hang forever depleeding my resources / processes.

Added timeout

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Entities/Shared/CustomData.py
paddle_billing/Entities/Subscriptions/SubscriptionItemsWithPrice.py
paddle_billing/Entities/Subscriptions/SubscriptionNonCatalogPrice.py
paddle_billing/Entities/Subscriptions/SubscriptionNonCatalogPriceWithProduct.py
paddle_billing/Entities/Subscriptions/SubscriptionNonCatalogProduct.py
paddle_billing/Resources/Subscriptions/Operations/PreviewUpdateSubscription.py
paddle_billing/Resources/Subscriptions/Operations/UpdateSubscription.py
tests/Functional/Resources/Subscriptions/_fixtures/request/preview_update_full.json
tests/Functional/Resources/Subscriptions/_fixtures/request/update_full.json
tests/Functional/Resources/Subscriptions/test_SubscriptionsClient.py

- Support custom prices when updating and previewing subscriptions, see [related changelog](https://developer.paddle.com/changelog/2024/add-custom-items-subscription)

feat: Support custom prices when updating and previewing subscriptions

---

CHANGELOG.md
paddle_billing/Entities/Shared/Disposition.py
paddle_billing/Entities/Shared/__init__.py
paddle_billing/Resources/Transactions/Operations/GetTransactionInvoice.py
paddle_billing/Resources/Transactions/Operations/__init__.py
paddle_billing/Resources/Transactions/TransactionsClient.py
tests/Functional/Resources/Transactions/test_TransactionsClient.py

- `TransactionsClient.get_invoice_pdf` now supports `disposition` parameter, see [related changelog](https://developer.paddle.com/changelog/2024/invoice-pdf-open-in-browser)

feat: Support disposition query parameter

---

CHANGELOG.md
paddle_billing/Resources/Customers/CustomersClient.py
tests/Functional/Resources/Customers/test_CustomersClient.py

- `CustomersClient.credit_balances` can now be filtered by `currency_code`

fix: Fix filtering of customer credit balances by currency code

---

CHANGELOG.md
paddle_billing/Entities/Event.py
paddle_billing/Notifications/Entities/SubscriptionCreated.py
tests/Functional/Resources/Events/test_EventsClient.py
tests/Unit/Entities/test_Event.py

- `paddle_billing.Entities.Event` `data` will now be `paddle_billing.Notifications.Entities.SubscriptionCreated` for `subscription.created` events

feat: Add SubscriptionCreated notification entity with transaction_id

---

CHANGELOG.md
paddle_billing/Entities/Shared/TransactionPaymentAttempt.py
tests/Functional/Resources/Events/_fixtures/response/list_default.json
tests/Functional/Resources/Events/test_EventsClient.py
tests/Functional/Resources/Transactions/_fixtures/response/full_entity.json
tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
tests/Functional/Resources/Transactions/test_TransactionsClient.py

- Transaction payments `payment_method_id` can be `string` or `None`

fix: Transaction payments payment_method_id can be string or None

---

CHANGELOG.md
paddle_billing/Entities/Event.py
paddle_billing/Entities/Notifications/NotificationEvent.py
paddle_billing/Notifications/Entities/Entity.py
paddle_billing/Notifications/Entities/EntityDict.py
paddle_billing/Notifications/Entities/UndefinedEntity.py
tests/Unit/Entities/Notifications/test_NotificationEvent.py
tests/Unit/Entities/test_Event.py

- Return `paddle_billing.Notifications.Entities.UndefinedEntity` for unknown notification entity types.
- `paddle_billing.Notifications.Entities.Entity` and `paddle_billing.Notifications.Entities.UndefinedEntity` implement common `EntityDict` protocol.

fix: Return UndefinedEntity for unknown notification entity types

---

CHANGELOG.md
paddle_billing/Client.py
tests/Functional/Client/test_Client.py

- Client connection errors will be raised as `requests.exceptions.ConnectionError` instead of an `AttributeError`
#54

fix: Handle connection errors

---

CHANGELOG.md
UPGRADING.md
setup.py

- Added `product` to `subscription.items[]`, see [related changelog](https://developer.paddle.com/changelog/2024/subscription-items-product?utm_source=dx&utm_medium=paddle-python-sdk)
- Support custom prices when updating and previewing subscriptions, see [related changelog](https://developer.paddle.com/changelog/2024/add-custom-items-subscription)
- Support for `custom_data` on discounts
- Support notification settings pagination, see [related changelog](https://developer.paddle.com/changelog/2024/notification-settings-pagination)
- Support notification settings `active` filter
- `TransactionsClient.get_invoice_pdf` now supports `disposition` parameter, see [related changelog](https://developer.paddle.com/changelog/2024/invoice-pdf-open-in-browser)
- `SubscriptionClient` `preview_update` …

docs(release): 0.3.0

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Entities/Shared/TransactionLineItemPreview.py
setup.py
tests/Functional/Resources/Transactions/_fixtures/response/preview_entity.json

- `paddle_billing.Entities.Shared.TransactionLineItemPreview` `proration` can now be None
- Note: `TransactionLineItemPreview` is used in a few places where `proration` varies (nullable / omitted). In the next major version we should create separate line item classes for each case.

fix: Support null proration on transaction line items

---

CHANGELOG.md
UPGRADING.md
paddle_billing/Client.py
setup.py

- `paddle_billing.Resources.Discounts.Operations.CreateDiscount` `expires_at` is now `paddle_billing.Entities.DateTime`
- `paddle_billing.Resources.Discounts.Operations.UpdateDiscount` `expires_at` is now `paddle_billing.Entities.DateTime`
- Transaction and Subscription operation items now allow optional properties to be omitted.
- The following property types have changed (See UPGRADING.md for further details)
- `paddle_billing.Resources.Subscriptions.Operations`:
- `UpdateSubscription.items`
- `PreviewUpdateSubscription.items`
- `CreateOneTimeCharge.items`
- `PreviewOneTimeCharge.items`
- `paddle_billing.Resources.Transactions.Operations`:
- `CreateTransaction.items`
- `UpdateTransaction.items`
- `PreviewTransactionByAddress.items`
- `PreviewTransactionByCustomer.items`
- …

docs(release): 1.0.0

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Entities/PaymentMethod.py
paddle_billing/Notifications/Entities/PaymentMethod.py
paddle_billing/Notifications/Entities/PaymentMethodDeleted.py
setup.py

- `paddle_billing.Entities.PaymentMethod` `type` property is required

fix: PaymentMethod type property is required

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Notifications/Entities/Subscription.py
paddle_billing/Notifications/Entities/SubscriptionCreated.py
setup.py

- `paddle_billing.Notifications.Entities.Subscription` and `paddle_billing.Notifications.Entities.SubscriptionCreated` `current_billing_period` would return `None` if `billing_details` was `None`. `current_billing_period` will now return `TimePeriod` when set.

fix: Subscription notification should always return billing period when set

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Entities/CustomerPortalSession.py
paddle_billing/Entities/CustomerPortalSessions/CustomerPortalSessionGeneralUrl.py
paddle_billing/Entities/CustomerPortalSessions/CustomerPortalSessionSubscriptionUrl.py
paddle_billing/Entities/CustomerPortalSessions/CustomerPortalSessionUrls.py
paddle_billing/Entities/CustomerPortalSessions/__init__.py
paddle_billing/Resources/CustomerPortalSessions/CustomerPortalSessionsClient.py
paddle_billing/Resources/CustomerPortalSessions/Operations/CreateCustomerPortalSession.py
paddle_billing/Resources/CustomerPortalSessions/Operations/__init__.py
tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_multiple.json
tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_single.json
tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_multiple.json
tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_single.json
tests/Functional/Resources/CustomerPortalSessions/test_CustomerPortalSessionsClient.py

- Support for customer portal sessions, see [related changelog](https://developer.paddle.com/changelog/2024/customer-portal-sessions?utm_source=dx&utm_medium=paddle-python-sdk)
- `Client.customer_portal_sessions.create`

feat: Add support for customer portal sessions

---

CHANGELOG.md
paddle_billing/Client.py
setup.py

- Support for customer portal sessions, see [related changelog](https://developer.paddle.com/changelog/2024/customer-portal-sessions?utm_source=dx&utm_medium=paddle-python-sdk)
- `Client.customer_portal_sessions.create`

docs: Release 1.2.0

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Entities/CustomerPortalSession.py
paddle_billing/Resources/CustomerPortalSessions/Operations/CreateCustomerPortalSession.py
paddle_billing/Resources/Notifications/NotificationsClient.py
setup.py
tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_empty.json
tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_empty.json
tests/Functional/Resources/CustomerPortalSessions/test_CustomerPortalSessionsClient.py
tests/Functional/Resources/Notifications/test_NotificationsClient.py

- Subscription IDs can be omitted when creating customer portal sessions
- Customer portal session customer ID will always be returned as string
- `Client.notifications.replay` now calls correct endpoint

fix: Customer portal sessions subscription IDs / Replay Endpoint

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Entities/Subscriptions/SubscriptionOnResume.py
paddle_billing/Entities/Subscriptions/__init__.py
paddle_billing/Resources/Subscriptions/Operations/PauseSubscription.py
paddle_billing/Resources/Subscriptions/Operations/ResumeSubscription.py
setup.py
tests/Functional/Resources/Subscriptions/_fixtures/request/pause_resume_existing_billing_period.json
tests/Functional/Resources/Subscriptions/_fixtures/request/pause_resume_new_billing_period.json
tests/Functional/Resources/Subscriptions/_fixtures/request/resume_existing_billing_period.json
tests/Functional/Resources/Subscriptions/_fixtures/request/resume_new_billing_period.json
tests/Functional/Resources/Subscriptions/test_SubscriptionsClient.py

- Added `on_resume` support to subscription resume and pause operations

feat: Add on_resume support to subscription resume and pause operations

---

CHANGELOG.md
paddle_billing/Client.py
paddle_billing/Resources/Transactions/Operations/PreviewTransaction.py
paddle_billing/Resources/Transactions/Operations/PreviewTransactionByCustomer.py
paddle_billing/Resources/Transactions/Operations/PreviewTransactionByIP.py
paddle_billing/Resources/Transactions/Operations/__init__.py
paddle_billing/Resources/Transactions/TransactionsClient.py
setup.py
tests/Functional/Resources/Transactions/_fixtures/request/preview_default_basic.json
tests/Functional/Resources/Transactions/_fixtures/request/preview_default_full.json
tests/Functional/Resources/Transactions/test_TransactionsClient.py

- Added `PreviewTransaction` operation to support transaction previews without location information.
- Transaction preview `currency_code` can now be set to `null`.

feat: Support transaction preview without location information

---

.github/workflows/lint.yml
.github/workflows/publish_to_pypi.yml
.github/workflows/release-on-push.yml
.github/workflows/testing.yml

Pin the github actions to specific commits.
This is considered good practice, in particular due to recent concerns over compromised actions

Pin github actions to commits

---

CHANGELOG.md
paddle_billing/Entities/Shared/TransactionPayoutTotals.py
paddle_billing/Entities/Shared/TransactionPayoutTotalsAdjusted.py
paddle_billing/Notifications/Entities/Shared/TransactionPayoutTotals.py
paddle_billing/Notifications/Entities/Shared/TransactionPayoutTotalsAdjusted.py
tests/Functional/Resources/Simulations/_fixtures/payload/transaction.completed.json
tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_one.json
tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_two.json
tests/Unit/Entities/_fixtures/notification/entity/transaction.completed.json
tests/Unit/Entities/_fixtures/notification/entity/transaction.revised.json

- Added `exchange_rate` and `fee_rate` to `TransactionPayoutTotals`
- Added `exchange_rate` to `TransactionPayoutTotalsAdjusted`

feat: Add `exchange_rate` and `fee_rate` to payout totals

---

CHANGELOG.md
paddle_billing/Client.py
setup.py

- Non-catalog discounts on Transactions, see [changelog](https://developer.paddle.com/changelog/2025/custom-discounts?utm_source=dx&utm_medium=paddle-python-sdk)
- Support `retained_fee` field on totals objects to show the fees retained by Paddle for the adjustment.
- Added support for new payment methods `blik`, `mb_way`, `pix` and `upi`. See [related changelog](https://developer.paddle.com/changelog/2025/blik-mbway-payment-methods?utm_source=dx&utm_medium=paddle-python-sdk).
- `ApiError` will now have `retry_after` property set for [too_many_requests](https://developer.paddle.com/errors/shared/too_many_requests?utm_source=dx&utm_medium=paddle-python-sdk) errors

docs(release): v1.11.0
